export const FETCH_SERIES_SEARCH_REQUEST = 'FETCH_SERIES_SEARCH_REQUEST'
export const FETCH_SERIES_SEARCH_SUCCESS = 'FETCH_SERIES_SEARCH_SUCCESS'
export const FETCH_SERIES_SEARCH_FAILURE = 'FETCH_SERIES_SEARCH_FAILURE'