export const FETCH_GENRE_MOVIES_REQUEST = 'FETCH_GENRE_MOVIES_REQUEST'
export const FETCH_GENRE_MOVIES_SUCCESS = 'FETCH_GENRE_MOVIES_SUCCESS'
export const FETCH_GENRE_MOVIES_FAILURE = 'FETCH_GENRE_MOVIES_FAILURE'